// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2319d7a678b044b3a31c00acbd87f23c233cfd73/karma-chai-sinon/karma-chai-sinon.d.ts
declare var should: Chai.Should;
declare var expect: Chai.ExpectStatic;
declare var assert: Chai.AssertStatic;
declare var sinon: Sinon.SinonStatic;
