service: pmg-6900-data-services

provider:
  name: aws
  runtime: nodejs4.3
  role: arn:aws:iam::093584548873:role/6900-Dev-Lambda-Execution-Role
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 20 # The default is 6
  deploymentBucket: 6900-pmg-dev-dropfolder
  stage: dev

package:
  individually: true
  exclude:
    - "**/*"
  include:
    - .env
    - ../pmg.services/utils/lambda-utils.js

functions:
  populate-assignee:
    handler: populateassignee/index.handler
    name: ${self:custom.prefix}-Populate-Assignee
    description: SERVERLESS-populates the assignee table
    package:
      include:
        - populateassignee/index.js
        - populateassignee/node_modules/**

  populate-assignee-profile-fam:
    handler: populateassigneeprofilefam/index.handler
    name: ${self:custom.prefix}-Populate-Assignee-Profile-Fam
    description: SERVERLESS-populates the assignmentprofilefam table
    package:
      include:
        - populateassigneeprofilefam/index.js
        - populateassigneeprofilefam/node_modules/**

  populate-country:
    handler: populatecountry/index.handler
    name: ${self:custom.prefix}-Populate-Country
    description: SERVERLESS-populates the CompanyToCountry table
    package:
      include:
        - populatecountry/index.js
        - populatecountry/node_modules/**

  populate-geographic-unit:
    handler: populategeographicunit/index.handler
    name: ${self:custom.prefix}-Populate-Geographic-Unit
    description: SERVERLESS-populates the GeographicUnit table
    package:
      include:
        - populategeographicunit/index.js
        - populategeographicunit/node_modules/**

  populate-journal:
    handler: populatejournal/index.handler
    name: ${self:custom.prefix}-Populate-Journal
    description: SERVERLESS-populates the Journal Transaction table
    package:
      include:
        - populatejournal/index.js
        - populatejournal/node_modules/**

  populate-journal-detail:
    handler: populatejournaldetail/index.handler
    name: ${self:custom.prefix}-Populate-Journal-Details
    description: SERVERLESS-populates the Journal Transaction Detail table
    package:
      include:
        - populatejournaldetail/index.js
        - populatejournaldetail/node_modules/**

  populate-s-country:
    handler: populatescountry/index.handler
    name: ${self:custom.prefix}-Populate-S-Country
    description: SERVERLESS-populates the sCountry table
    package:
      include:
        - populatescountry/index.js
        - populatescountry/node_modules/**
        
custom:
   stage: ${opt:stage, self:provider.stage, env:USER}
   prefix: 6900-PMG-${self:custom.stage}

plugins:
  - serverless-mocha-plugin
  - serverless-offline
  
