// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-changed/gulp-changed.d.ts
declare module "gulp-changed"
{
    import { Transform } from "stream";
    import File = require("vinyl");

    interface IComparator
    {
        /**
         * @param stream Should be used to queue sourceFile if it passes some comparison
         * @param callback Should be called when done
         * @param sourceFile File to operate on
         * @param destPath Destination for sourceFile as an absolute path
         */
        (stream: Transform, callback: Function, sourceFile: File, destPath: string): void;
    }

    interface IDestination
    {
        (file: string|Buffer): string;
    }

    interface IOptions
    {
        /**
         * The working directory the folder is relative to.
         * @default process.cwd()
         */
        cwd?: string;

        /**
         * Extension of the destination files.
         */
        extension?: string;

        /**
         * Function that determines whether the source file is different from the destination file.
         * @default changed.compareLastModifiedTime
         */
        hasChanged?: IComparator;
    }

    interface IGulpChanged
    {
        (destination: string|IDestination, options?: IOptions): NodeJS.ReadWriteStream;

        compareLastModifiedTime: IComparator;
        compareSha1Digest: IComparator;
    }

    const changed: IGulpChanged;
    export = changed;
}
