// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-csso/gulp-csso.d.ts
declare module 'gulp-csso' {
    function csso(structureMinimization?: boolean): NodeJS.ReadWriteStream;
    namespace csso {}
    export = csso;
}
