service: pmg-6900

provider:
  name: aws
  runtime: nodejs4.3
  role: arn:aws:iam::093584548873:role/6900-Dev-Lambda-Execution-Role
  memorySize: 256 # Overwrite the default memory size. Default is 1024
  timeout: 10 # The default is 6
  deploymentBucket: 6900-pmg-dev-dropfolder
  stage: dev

package:
  individually: true
  exclude:
    - "**/*"
  include:
    - .env

functions:
  get-accounts:
    handler: account/get-accounts.handler
    name: ${self:custom.prefix}-GET-Accounts
    description: SERVERLESS-Returns a list of 10 Accounts with Number and Name
    events:
      - http:
          path: accounts
          method: get
    package:
      include:
        - account/get-accounts.js
        - account/node_modules/**
        
  get-assignee-names:
    handler: assignee/get-assignee-names.handler
    name: ${self:custom.prefix}-GET-Assignee-Names
    description: SERVERLESS-Returns a list of 10 Assignee Names based on specified value
    events:
      - http:
          path: assigneeNames
          method: get
    package:
      include:
        - assignee/get-assignee-names.js
        - assignee/node_modules/**

  get-assignee-personnel-numbers:
    handler: assignee/get-assignee-personnel-numbers.handler
    name: ${self:custom.prefix}-GET-Assignee-Personnel-Numbers
    description: SERVERLESS-Returns a list of 10 Assignee Personnel Numbers based on specified value
    events:
      - http:
          path: assigneePersonnelNumbers
          method: get
    package:
      include:
        - assignee/get-assignee-personnel-numbers.js
        - assignee/node_modules/**

  get-company-codes:
    handler: company/get-company-codes.handler
    name: ${self:custom.prefix}-GET-Company-Codes
    description: SERVERLESS-Returns a list of Company Codes based on enterprise id
    events:
      - http:
          path: companyCodes
          method: get
    package:
      include:
        - company/get-company-codes.js
        - company/node_modules/**

  get-company-names:
    handler: company/get-company-names.handler
    name: ${self:custom.prefix}-GET-Company-Names
    description: SERVERLESS-Returns a list of Company Names
    events:
      - http:
          path: companyNames
          method: get
    package:
      include:
        - company/get-company-names.js
        - company/node_modules/**

  
  get-countries:
    handler: location/get-countries.handler
    name: ${self:custom.prefix}-GET-Countries
    description: SERVERLESS-Returns a list of Countries
    events:
      - http:
          path: countries
          method: get
    package:
      include:
        - location/get-countries.js
        - location/node_modules/**

  get-geographic-units:
    handler: location/get-geographic-units.handler
    name: ${self:custom.prefix}-GET-Geographic-Units
    description: SERVERLESS-Returns a list of Geographic Units
    events:
      - http:
          path: geographicUnits
          method: get
    package:
      include:
        - location/get-geographic-units.js
        - location/node_modules/**

  get-sending-company-codes:
    handler: company/get-sending-company-codes.handler
    name: ${self:custom.prefix}-GET-Sending-Company-Codes
    description: SERVERLESS-Returns a list of Sending Company Codes
    events:
      - http:
          path: sendingCompanyCodes
          method: get
    package:
      include:
        - company/get-sending-company-codes.js
        - company/node_modules/**

custom:
   stage: ${opt:stage, self:provider.stage, env:USER}
   prefix: 6900-PMG-${self:custom.stage}

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: 6900-PMG-${self:custom.stage}