service: pmg-6900

provider:
  name: aws
  runtime: nodejs4.3
  role: arn:aws:iam::093584548873:role/6900-Dev-Lambda-Execution-Role
  memorySize: 256 # Overwrite the default memory size. Default is 1024
  timeout: 10 # The default is 6
  deploymentBucket: 6900-pmg-dev-dropfolder
  stage: dev

package:
  individually: true
  exclude:
    - "**/*"
  include:
    - .env

functions:
  get-accounts:
    handler: account/get-accounts.handler
    name: ${self:custom.prefix}-GET-Accounts
    description: SERVERLESS-Returns a list of 10 Accounts with Number and Name
    events:
      - http:
          path: accounts
          method: get
    package:
      include:
        - account/get-accounts.js
        - account/node_modules/**
        
  get-assignee-names:
    handler: assignee/get-assignee-names.handler
    name: ${self:custom.prefix}-GET-Assignee-Names
    description: SERVERLESS-Returns a list of 10 Assignee Names based on specified value
    events:
      - http:
          path: assigneeNames
          method: get
    package:
      include:
        - assignee/get-assignee-names.js
        - assignee/node_modules/**

  get-assignee-personnel-numbers:
    handler: assignee/get-assignee-personnel-numbers.handler
    name: ${self:custom.prefix}-GET-Assignee-Personnel-Numbers
    description: SERVERLESS-Returns a list of 10 Assignee Personnel Numbers based on specified value
    events:
      - http:
          path: assigneePersonnelNumbers
          method: get
    package:
      include:
        - assignee/get-assignee-personnel-numbers.js
        - assignee/node_modules/**

custom:
   stage: ${opt:stage, self:provider.stage, env:USER}
   prefix: 6900-PMG-${self:custom.stage}

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: 6900-PMG-${self:custom.stage}